#!/bin/bash
echo -e "\nSetting fuses...\n"
avrdude -c stk500v1 -P /dev/ttyUSB0 -p m168p -b 19200 -U efuse:w:0xfc:m -U hfuse:w:0xdf:m -U lfuse:w:0xe2:m
echo -e "\nUploading bootloader..\n"
avrdude -c stk500v1 -P /dev/ttyUSB0 -p m168p -b 19200 -U flash:w:./boot/boot_atmega168p.hex:i
echo -e "Complete!\n"
